config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :users do
    resources :dashboard, only: [:index]
    
    devise_scope :user do 
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  resources :relationships, only: [:create, :destroy]
  post 'accept_friend', to: 'relationships#accept_friend', as: 'accept_friend'
  post 'refused_friend', to: 'relationships#refused_friend', as: 'refused_friend'

  post 'update_status', to: 'users#update_status', as: 'update_status'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'get_highschool_district_ajax', to: 'users#get_highschool_district_ajax', as: 'get_highschool_district_ajax'
  post 'get_highschool_list_ajax', to: 'users#get_highschool_list_ajax', as: 'get_highschool_list_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'delete_status_ajax', to: 'users#delete_status_ajax', as: 'delete_status_ajax'

  get ':username', to: 'users#show', as: :user
  
  devise_for :users, path: 'users', controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
end

app/controllers/users/access_controller.rb
class Users::AccessController < ApplicationController
  before_action :authenticate_user!
  before_action :set_global_layout
  
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end

  def set_global_layout
    @is_global_layout = true
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::AccessController
  def index
    @user = current_user

    suggestions_user = []
    User.all.each do |user|
      if ( @user != user ) && ( !@user.is_friend? user )
        user.trust_point += @user.match_point( user )
        suggestions_user << user
      end
    end
    @new_suggestions_point = suggestions_user.sort { |x,y| y[:trust_point] <=> x[:trust_point] }.take(5)

    wall_list = []
    User.all.each do |user|
      if ( @user == user ) || ( @user.is_friend? user )
        activities = user.activities.order('created_at DESC')
        activities.each do |activity|
          wall_list << { type: "activity", target: activity }
        end

        statuses = user.statuses.order('created_at DESC')
        statuses.each do |status|
          wall_list << { type: "statuses", target: status }
        end
      end
    end

    @new_wall_list = wall_list.sort { |x,y| y[:target].created_at <=> x[:target].created_at }.take(50)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout :user_layout

  def send_instructions_successfull
  end

  protected
  def user_layout
    "users/layouts/application"
  end

  def after_sending_reset_password_instructions_path_for(resource_name)
    users_send_instructions_successfull_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :set_global_layout, only: :edit

  layout :user_layout

  def destroy  
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)  
    set_flash_message :notice, :destroyed if is_flashing_format?  
    yield resource if block_given?  
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }  
  end 

  protected
  def user_layout
    "users/layouts/application"
  end

  def set_global_layout
    @is_global_layout = true
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  layout :user_layout

  protected
  def user_layout
    "users/layouts/application"
  end
end

app/controllers/users_controller.rb
class UsersController < Users::AccessController
  include UsersHelper
  before_action :show_user, only: :show
  before_action :set_user, except: [
    :show, 
    :get_district_ajax, 
    :get_commune_ajax, 
    :get_highschool_district_ajax, 
    :get_highschool_list_ajax,
    :check_username_ajax,
    :delete_status_ajax,
    :update_status,
    :send_friend_request,
    :cancel_friend_request
  ]

  def show
    redirect_to users_dashboard_index_path unless @user
    @activities = @user.activities.limit(7).order('created_at DESC')
    @user_status = @user.statuses.limit(10).order('created_at DESC')

    if @user == current_user
      @jobs = get_job_list
      @like_dislike_list = get_like_dislike_list
      @university_list = get_university_list
      
      @address_province_list = ActiveSupport::JSON.decode(File.read('databases/address_province.json'))
      @distric_list_of_province = get_district_list(@user.address_province)
      @commune_list_of_province = get_commune_list(@user.address_province, @user.address_district)

      @address_highschool_province_list = ActiveSupport::JSON.decode(File.read('databases/address_province.json'))
      @address_highschool_district_list = get_district_list(@user.highschool_province)
      @highschool_list = get_school_list(@user.highschool_province, @user.highschool_district)
    end
  end

  def upload_avatar
    if @user == current_user
      respond_to do |format|
        unless params[:user].blank?
          @user.add_point( 20 ) if @user.avatar.blank?
          if @user.update(user_avatar_params)
            @user.reload
            set_activity(@user, "update avatar", nil)
          end
        end
        format.js {}
      end
    end
  end

  def update_information
    if @user == current_user
      infor_params = user_information_params.to_h
      infor_params[:job].shift
      if @user.job.blank?
        job_point = infor_params[:job].length
      else
        if infor_params[:job].length > @user.job.split("|").length
          job_point = infor_params[:job].length - @user.job.split("|").length
        else
          job_point = 0
        end
      end
      @user.add_point( job_point*5 )
      infor_params[:job] = infor_params[:job].join("|")
      infor_params[:hobby].shift
      if @user.hobby.blank?
        hobby_point = infor_params[:hobby].length
      else
        if infor_params[:hobby].length > @user.hobby.split("|").length
          hobby_point = infor_params[:hobby].length - @user.hobby.split("|").length
        else
          hobby_point = 0
        end
      end
      @user.add_point( hobby_point*5 )
      infor_params[:hobby] = infor_params[:hobby].join("|")
      infor_params[:dislike].shift
      if @user.dislike.blank?
        dislike_point = infor_params[:dislike].length
      else
        if infor_params[:dislike].length > @user.dislike.split("|").length
          dislike_point = infor_params[:dislike].length - @user.dislike.split("|").length
        else
          dislike_point = 0
        end
      end
      @user.add_point( dislike_point*5 )
      infor_params[:dislike] = infor_params[:dislike].join("|")

      @user.add_point( 10 ) if ( @user.username.blank? && !infor_params[:username].blank? )
      @user.add_point( 10 ) if ( @user.name.blank? && !infor_params[:name].blank? )
      @user.add_point( 10 ) if ( @user.gender.blank? && !infor_params[:gender].blank? )
      @user.add_point( 10 ) if ( @user.dob.blank? && !infor_params[:dob].blank? )
      @user.add_point( 10 ) if ( @user.address_commune.blank? && !infor_params[:address_commune].blank? )
      @user.add_point( 10 ) if ( @user.address_district.blank? && !infor_params[:address_district].blank? )
      @user.add_point( 10 ) if ( @user.address_province.blank? && !infor_params[:address_province].blank? )
      @user.add_point( 10 ) if ( @user.highschool_province.blank? && !infor_params[:highschool_province].blank? )
      @user.add_point( 10 ) if ( @user.highschool_district.blank? && !infor_params[:highschool_district].blank? )
      @user.add_point( 10 ) if ( @user.high_school.blank? && !infor_params[:high_school].blank? )
      @user.add_point( 10 ) if ( @user.univesity.blank? && !infor_params[:univesity].blank? )

      respond_to do |format|
        if @user.update(infor_params)
          @user.reload
          set_activity(@user, "update information", nil)
        end
        format.js {}
      end
    end
  end

  def update_status
    if current_user.id == user_update_status_params[:user_id].to_i && !user_update_status_params[:status].blank?
      respond_to do |format|
        @status = Status.new(user_update_status_params)
        if @status.save
          @status.reload
          set_activity(@status.user, "update status", nil)
        end

        format.js {}
      end
    end
  end

  def get_district_ajax
    render json: { 'distric_list': get_district_list(params['province']) }
  end

  def get_commune_ajax
    render json: { 'commune_list': get_commune_list(params['province'], params['district']) }
  end

  def get_highschool_district_ajax
    render json: { 'distric_list': get_district_list(params['province']) }
  end

  def get_highschool_list_ajax
    render json: { 'school_list': get_school_list(params['province'], params['district']) }
  end

  def check_username_ajax
    if params['username'] != current_user.username
      is_valid = User.new(email: 'user@example.com', password: '123456789', password_confirmation: '123456789', username: params['username']).valid?
      render json: { 'is_valid': is_valid }
    else
      render json: { 'is_valid': true }
    end
  end

  def delete_status_ajax
    status = Status.find_by_id( params[:status_id].to_i )
    if !status.nil? && status.user == current_user
      render json: { 'success': true, 'status_id': params[:status_id] } if status.destroy
    else
      render json: { 'success': false }
    end
  end

  private

  def show_user
    @user = User.find_by_username( params[:username] )
    @user = User.find_by_id( params[:username] ) unless @user
  end

  def set_user
    @user = User.find params[:id]
  end

  def user_information_params
    params.require(:user).permit(:username, :name, :gender, :dob, { :job => [] }, { :hobby => [] }, { :dislike => [] }, :address_commune, :address_district, :address_province, :highschool_province, :highschool_district, :high_school, :univesity)
  end

  def user_avatar_params
    params.require(:user).permit(:avatar)
  end

  def user_update_status_params
    params.require(:status).permit(:status, :user_id)
  end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def get_district_list province
    distric_list = ActiveSupport::JSON.decode(File.read('databases/address_district.json'))
    distric_list_of_province = []
    distric_list.each do |district|
      distric_list_of_province << district if district['Ten_Tinh_Thanh_Pho'] == province
    end

    return distric_list_of_province
  end

  def get_commune_list(province, district)
    commune_list = ActiveSupport::JSON.decode(File.read('databases/address_commune.json'))
    commune_list_of_province = []
    commune_list.each do |commune|
      if commune['Ten_Tinh_Thanh_Pho'] == province && commune['Ten_Quan_Huyen'] == district
        commune_list_of_province << commune 
      end
    end

    return commune_list_of_province
  end

  def get_school_list(province, district)
    school_list = ActiveSupport::JSON.decode(File.read('databases/highschool_list.json'))
    school_list_fil = []
    school_list.each do |school|
      unless province.nil? && district.nil?
        if ( (province.include? school['Ten_Tinh']) || (school['Ten_Tinh'].include? province) ) && ( (school['Ten_Quan_Huyen'].include? district) || (district.include? school['Ten_Quan_Huyen']) )
          school_list_fil << school 
        end
      end
    end

    return school_list_fil
  end

  def get_school_address user
    highschool_list = get_school_list(user.highschool_province, user.highschool_district)
    school_address = ""
    highschool_list.each do |highschool|
      school_address = "#{highschool['Dia_Chi']} - #{highschool['Ten_Tinh']}" if highschool['Ten_Truong'] == user.high_school
    end

    return school_address
  end

  def get_job_list
    jobs = []
    File.readlines('databases/job_list.txt').map do |line|
      jobs << line.split("\r\n")[0]
    end

    return jobs
  end

  def get_university_list
    university_list = []
    File.readlines('databases/univesity_list.txt').map do |line|
      university_list << line.split("\r\n")[0]
    end

    return university_list
  end

  def get_like_dislike_list
    like_dislike_list = []
    File.readlines('databases/like_disklike_list.txt').map do |line|
      like_dislike_list << line.split("\r\n")[0]
    end
    like_dislike_list = like_dislike_list.uniq

    return like_dislike_list
  end

  def set_activity(user, type, target )
    unless ( type.blank? && user.blank? )
      if target.blank?
        Activity.create(activity_type: type, user_id: user.id )
      else
        Activity.create(activity_type: type, user_id: user.id, activity_target: target.id )
      end
    end
  end
end

app/views/users/_accept_request.html.erb
<a href="#" data-toggle="modal" data-target="#acceptFriendModal" class="btn btn-success make-friend-btn no-outline">
  Accept request
</a>
<div class="modal fade" id="acceptFriendModal" tabindex="-1" role="dialog" aria-labelledby="cancelFriendModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelFriendModalLabel">Are you sure ?</h5>
        <button type="button" class="close cursor-pointer no-outline" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Accept friend request from <%= stick_avatar_for user_target %>
      </div>
      <div class="modal-footer">
        <%= form_tag( refused_friend_path , method: :post, remote: true, authenticity_token: true ) do %>
          <%= hidden_field_tag 'user_id', user_target.id %>
          <button type="submit" class="btn btn-danger cursor-pointer no-outline">decline</button>
        <% end %>
        <%= form_tag( accept_friend_path , method: :post, remote: true, authenticity_token: true ) do %>
          <%= hidden_field_tag 'user_id', user_target.id %>
          <button type="submit" class="btn btn-success cursor-pointer no-outline">accept</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_pending_accept.html.erb
<%= form_for(current_user.active_relationships.find_by(receive_user_id: user_target.id), html: { method: :delete }, remote: true, authenticity_token: true) do |f| %>
  
  <a href="#" data-toggle="modal" data-target="#cancelFriendModal" class="btn btn-warning make-friend-btn no-outline">
    Pending accept
  </a>
  <div class="modal fade" id="cancelFriendModal" tabindex="-1" role="dialog" aria-labelledby="cancelFriendModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="cancelFriendModalLabel">Are you sure ?</h5>
          <button type="button" class="close cursor-pointer no-outline" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Cancel your friend request to <%= stick_avatar_for user_target %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary cursor-pointer no-outline" data-dismiss="modal">No</button>
          <button type="submit" class="btn btn-primary cursor-pointer no-outline">Yes</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_send_request.html.erb
<%= form_for(current_user.active_relationships.build, remote: true, authenticity_token: true) do |f| %>
  <%= hidden_field_tag :receive_user_id, user_target.id %>
  
  <a href="#" data-toggle="modal" data-target="#makeFriendModal" class="btn btn-primary make-friend-btn no-outline">
    Send friend request
  </a>
  <div class="modal fade" id="makeFriendModal" tabindex="-1" role="dialog" aria-labelledby="makeFriendModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="makeFriendModalLabel">Are you sure ?</h5>
          <button type="button" class="close cursor-pointer no-outline" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Send friend request to <%= stick_avatar_for user_target %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary cursor-pointer no-outline" data-dismiss="modal">No</button>
          <button type="submit" class="btn btn-primary cursor-pointer no-outline">Yes</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_status_box.html.erb
<ul class='status-list'>
  <% status_list.each do |status| %>
    <%= render 'users/status_show', status_target: status %>
  <% end %>
</ul>

app/views/users/_status_show.html.erb
<li class="status-item" data-status-id="<%= status_target.id %>">
  <div class="table-panel">
    <div class="table-child status-avatar-box ver-top">
      <div class="status-user-avatar">
        <%= avatar_for status_target.user %>
      </div>
    </div>
    <div class="table-child ver-top">
      <p class="status-time">
        <%= status_target.created_at.in_time_zone('Hanoi').strftime("%Y %b %d %H:%M") %>
        <% if status_target.user == current_user %>
          <button type="button" class="delete-status no-outline cursor-pointer" data-toggle="modal" data-target="#deleteStatusModal_<%= status_target.id %>" >
            Delete 
            <i class="fa fa-trash" aria-hidden="true"></i>
          </button>
        <% end %>
      </p>
      <% if status_target.user == current_user %>
        <div class="modal fade" id="deleteStatusModal_<%= status_target.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteStatusModalLabel_<%= status_target.id %>" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteStatusModalLabel_<%= status_target.id %>">Are you sure?</h5>
                <button type="button" class="close no-outline cursor-pointer" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary no-outline cursor-pointer" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary no-outline cursor-pointer js--delete-status" data-status-id="<%= status_target.id %>">Yes</button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="status-user-content">
        <p><%= status_target.status %></p>
      </div>
    </div>
  </div>
</li>

app/views/users/_user_information_show.html.erb
<div class="user-information">
  <ul class="user-information-list list-unstyled">
    <% if user_target.username? %>
      <li class="username"><%= link_to "@#{user_target.username}", user_path( user_target.username ), class: "user-name-link" %></li>
    <% end %>
    <li class="name-or-email"><%= user_target.name? ? user_target.name : user_target.email %></li>
    <% if user_target.gender? %>
      <li class="gender-icon">
        <% if user_target.gender == "male" %>
          <i class="fa fa-mars" aria-hidden="true"></i>
        <% elsif user_target.gender == "female" %>
          <i class="fa fa-venus" aria-hidden="true"></i>
        <% end %>
      </li>
    <% end %>
    <% if user_target.dob? %>
      <li class="infor-line text-center"><b><%= user_target.dob.strftime("%Y %B %d") %> - <%= user_target.get_age %> years old </b></li>
    <% end %>
    <% if user_target.address_commune? || user_target.address_district? || user_target.address_province? %>
      <li class="infor-line">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            Address:
          </div>
          <div class="table-child ver-mid">
            <%= address_for user_target %>
          </div>
        </div>
      </li>
    <% end %>
    <% if user_target.job? %>
      <li class="infor-line">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            Job:
          </div>
          <div class="table-child ver-mid">
            <%= user_target.job.gsub('|', ', ') %>
          </div>
        </div>
      </li>
    <% end %>
    <% if user_target.hobby? %>
      <li class="infor-line">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            Hobby:
          </div>
          <div class="table-child ver-mid">
            <%= user_target.hobby.gsub('|', ', ') %>
          </div>
        </div>
      </li>
    <% end %>
    <% if user_target.dislike? %>
      <li class="infor-line">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            Dislike:
          </div>
          <div class="table-child ver-mid">
            <%= user_target.dislike.gsub('|', ', ') %>
          </div>
        </div>
      </li>
    <% end %>
    <% if user_target.high_school? %>
      <li class="infor-line">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            High school:
          </div>
          <div class="table-child ver-mid">
            <%= user_target.high_school %>
            <span class="address-highschool">( Address: <%= get_school_address user_target %> )</span>
          </div>
        </div>
      </li>
    <% end %>
    <% if user_target.univesity? %>
      <li class="infor-line infor-last-child">
        <div class="table-panel">
          <div class="table-child ver-mid infor-label">
            University:
          </div>
          <div class="table-child ver-mid">
            <%= user_target.univesity %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/update_information.js.erb
$('#editUserInformationModal').modal('hide');
$('#userInformationComboBox').html('<%= j render "user_information_show", user_target: @user %>');

if (location.pathname.replace("/", "") != "<%= @user.username %>") {
  window.location.href = "/<%= @user.username %>"
}

app/views/users/update_status.js.erb
$('.status-list').prepend("<%= j render 'status_show', status_target: @status %>");
$('#status_status').val('');

app/views/users/upload_avatar.js.erb
<% if remotipart_submitted? %>
  $('body').removeClass('over-flow-open');
  $('#userAvatarBox').html('<%= j avatar_for @user %>');
  $('#editUserAvatarModal #user_avatar').val('');
  $("#preview_image").empty();
  $('.js--add-image').show();
  $('.over-loader').hide();
<% else %>
  $('body').removeClass('over-flow-open');
  $('#editUserAvatarModal #user_avatar').val('');
  $("#preview_image").empty();
  $('.js--add-image').show();
  $('.over-loader').hide();
<% end %>