config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :users do
    resources :dashboard, only: [:index]
    
    devise_scope :user do 
      get '/password/send_instructions' => 'passwords#send_instructions_successfull', as: 'send_instructions_successfull'
    end
  end

  patch 'update_information/:id', to: 'users#update_information', as: 'update_information'
  put 'update_information/:id', to: 'users#update_information'

  patch 'upload_avatar/:id', to: 'users#upload_avatar', as: 'upload_avatar'
  put 'upload_avatar/:id', to: 'users#upload_avatar'

  resources :relationships, only: [:create, :destroy]
  post 'accept_friend', to: 'relationships#accept_friend', as: 'accept_friend'
  post 'refused_friend', to: 'relationships#refused_friend', as: 'refused_friend'

  post 'update_status', to: 'users#update_status', as: 'update_status'

  post 'get_district_ajax', to: 'users#get_district_ajax', as: 'get_district_ajax'
  post 'get_commune_ajax', to: 'users#get_commune_ajax', as: 'get_commune_ajax'
  post 'get_highschool_district_ajax', to: 'users#get_highschool_district_ajax', as: 'get_highschool_district_ajax'
  post 'get_highschool_list_ajax', to: 'users#get_highschool_list_ajax', as: 'get_highschool_list_ajax'
  post 'check_username_ajax', to: 'users#check_username_ajax', as: 'check_username_ajax'
  post 'delete_status_ajax', to: 'users#delete_status_ajax', as: 'delete_status_ajax'

  get ':username', to: 'users#show', as: :user
  
  devise_for :users, path: 'users', controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/views/home/index.html.erb
<div class="home-screen">
  <div id="parallaxBackground" class="mouse-parallax-bg"></div>
  <div class="home-content">
    <div class="container">
      <div class="row height-100vh align-items-center">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-6 col-sm-10 col-xs-12">
              <h1 class="main-text-logo text-center header-font">Make Friend Around The World</h1>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-4 col-sm-10 col-xs-12 home-nav-box">
              <% if user_signed_in? %>
                <%= link_to "Go to Dashboard", users_dashboard_index_path, class: "btn btn-outline-light btn-lg btn-block" %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light btn-lg btn-block" %>
              <% else %>
                <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-light btn-lg btn-block" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light btn-lg btn-block margin-top-20" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>